DROP TABLE IF EXISTS tracks;

CREATE TABLE tracks (
    id INTEGER PRIMARY_KEY AUTOINCREMENT,
    dance DECIMAL NOT NULL,
    energy DECIMAL NOT NULL,
    loud DECIMAL NOT NULL,
    val DECIMAL NOT NULL

)